export const ReservationList = () => {
   return(
    <>
     <div>
       <p>ドラフター内オーブン(左)</p>
       <p>ドラフター内オーブン(右)</p>
       <p>真空乾燥機(左)</p>
       <p>真空乾燥機(中)</p>
       <p>真空乾燥機(右)</p>
       <p>ホットプレス</p>
       <p>UV照射器</p>
       <p>オートグラフ</p>
       <p>TGA</p>
       <p>DTA</p>
       <p>DSC-60</p>
       <p>DMA</p>
       <p>ホットスターラー(熱電対)</p>
       <p>ホットスターラー</p>
     </div>    
    </>
   ) 
}